import type { Metadata } from "next";
import {Beiruti } from "next/font/google"; // get arabic font
import "./globals.css";
import { NavBar } from "@/components";

const beiruti = Beiruti({
  variable: "--font-beiruti",
  subsets: ["arabic"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      dir="rtl"
        className={` ${beiruti.variable} antialiased container mx-auto`}
      >
        <NavBar />
        {children}
      </body>
    </html>
  );
}
