export {default as NavBar} from "./NavBar/NavBar";
export {default as Select} from "./genericrs/Select";   
export {default as Option} from "./genericrs/Option";
export {default as Input} from "./genericrs/Input";
export {default as Button} from "./genericrs/Button";
export {default as Footer} from './Footer/Footer';
export {default as MainLogin} from './MainLogin/MainLogin';
export {default as Modal} from "./genericrs/Modal";
export {default as Cart} from "./genericrs/Cart";