export const city = [
  { id: 1, value: "الرياض", label: "الرياض" },
  { id: 2, value: "جدة", label: "جدة" },
  { id: 3, value: "الدمام", label: "الدمام" },
  { id: 4, value: "الخبر", label: "الخبر" },
  { id: 5, value: "القصيم", label: "القصيم" },
  { id: 6, value: "الطائف", label: "الطائف" },
  { id: 7, value: "مكة", label: "مكة" },
  { id: 8, value: "الطائف", label: "الطائف " },
  { id: 9, value: "المدينة", label: "المدينة" },
  { id: 10, value: "الجبيل", label: "الجبيل" },
  { id: 11, value: "الخرج", label: "الخرج" },
  { id: 12, value: "الظهران", label: "الظهران" },
  { id: 13, value: "الجوف", label: "الجوف" },
  { id: 14, value: "الحفر", label: "الحفر" },
  { id: 15, value: "الباحة", label: "الباحة" },
  { id: 16, value: "الجوف", label: "الجوف" },
  { id: 17, value: "الحفر", label: "الحفر" },
  { id: 18, value: "الباحة", label: "الباحة" },
  { id: 19, value: "الجوف", label: "الجوف" },
  { id: 20, value: "الحفر", label: "الحفر" },
];

// branches data
export const branches = [
  {
    id: 1,
    value: "الرياض",
    title: "فرع الروابي",
    map: "الروابي - شارع الروابي - بجوار محطة القطار",
    status: "OPEN",
  },
  {
    id: 2,
    value: "جدة",
    title: "فرع جدة",
    map: "جدة - شارع جدة - بجوار محطة القطار",
    status: "CLOSED",
  },
  {
    id: 3,
    value: "الدمام",
    title: "فرع الدمام",
    map: "الدمام - شارع الدمام - بجوار محطة القطار",
    status: "OPEN",
  },
  {
    id: 4,
    value: "الخبر",
    title: "فرع الخبر",
    map: "الخبر - شارع الخبر - بجوار محطة القطار",
    status: "OPEN",
  },
  {
    id: 5,

    value: "القصيم",
    title: "فرع القصيم",
    map: "القصيم - شارع القصيم - بجوار محطة القطار",
    status: "CLOSED",
  },
  {
    id: 6,
    value: "الطائف",
    title: "فرع الطائف",
    map: "الطائف - شارع الطائف - بجوار محطة القطار",
    status: "OPEN",
  },
  {
    id: 7,
    value: "الطائف",
    title: "فرع الطائف",
    map: "الطائف - شارع الطائف - بجوار محطة القطار",
    status: "CLOSED",
  },
  {
    id: 8,
    value: "الطائف",
    title: "فرع الطائف",
    map: "الطائف - شارع الطائف - بجوار محطة القطار",
    status: "OPEN",
  },
  {
    id: 9,
    value: "الطائف",
    title: "فرع الطائف",
    map: "الطائف - شارع الطائف - بجوار محطة القطار",
    status: "OPEN",
  },
  {
    id: 10,
    value: "الطائف",
    title: "فرع الطائف",
    map: "الطائف - شارع الطائف - بجوار محطة القطار",
    status: "CLOSED",
  },
  {
    id: 11,
    value: "الطائف",
    title: "فرع الطائف",
    map: "الطائف - شارع الطائف - بجوار محطة القطار",
    status: "CLOSED",
  },
  {
    id: 12,
    value: "الطائف",
    title: "فرع الطائف",
    map: "الطائف - شارع الطائف - بجوار محطة القطار",
    status: "OPEN",
  },
];
